version: "2"
networks:
  default:
    driver: bridge
    external:
      name: dev
services:
  dev-nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: dev-nacos
    hostname: nacos
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - dev-nacos-mysql
    restart: on-failure

  dev-nacos-mysql:
    container_name: dev-nacos-mysql
    image: nacos/nacos-mysql:${NACOS_MYSQL_VERSION}
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  dev-redis:
    image: redis:${REDIS_VERSION}
    container_name: dev-redis
    ports:
      - "6379:6379"
    restart: always

  dev-rabbitmq:
    container_name: dev-rabbitmq
    image: rabbitmq:${RABBITMQ_VERSION}
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=guest  # 账号
      - RABBITMQ_DEFAULT_PASS=guest  # 密码
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    restart: always

  dev-prometheus:
    container_name: dev-prometheus
    image: prom/prometheus:${LATEST}
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - dev-nacos
    restart: on-failure

  dev-grafana:
    container_name: dev-grafana
    image: grafana/grafana:${LATEST}
    ports:
      - "3000:3000"
    restart: on-failure

  dev-sentinel:
    image: fxbin/sentinel-dashboard:${SENTINEL_VERSION}
    container_name: dev-sentinel
    ports:
      - "8858:8858"
    expose:
      - "8858"
    restart: on-failure

  dev-es:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: dev-es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "TAKE_FILE_OWNERSHIP=true" #volumes 挂载权限 如果不想要挂载es文件改配置可以删除
      - "discovery.type=single-node" #单机模式启动
      - "TZ=Asia/Shanghai" # 设置时区
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 设置jvm内存大小
    ulimits:
      memlock:
        soft: -1
        hard: -1

  dev-elastichd:
    image: kylin2020/elastichd
    container_name: dev-elastichd
    ports:
      - "9800:9800"
    restart: on-failure

  dev-skywalking-oap:
    image: apache/skywalking-oap-server:${SKYWALKING_OAP_VERSION}
    container_name: dev-skywalking-oap
    restart: always
    depends_on:
      - dev-es
    links:
      - dev-es
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: dev-es:9200

  dev-skywalking-ui:
    image: apache/skywalking-ui:${SKYWALKING_UI_VERSION}
    container_name: dev-skywalking-ui
    restart: always
    depends_on:
      - dev-skywalking-oap
    links:
      - dev-skywalking-oap
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: http://dev-skywalking-oap:12800
