version: "2"
networks:
  default:
    external:
      name: dev
services:
  dev-nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: dev-nacos
    hostname: nacos
    env_file:
      - $PWD/env/nacos-standlone-mysql.env
    volumes:
      - $PWD/standalone-logs/:/home/nacos/logs
      - $PWD/init.d/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - dev-mysql
    restart: on-failure

  dev-mysql:
    image: mysql:${LATEST}
    container_name: dev-mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nacos
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - $PWD/mysql/data/:/var/lib/mysql/
      - $PWD/mysql/conf/:/etc/mysql/conf.d/
      - $PWD/mysql/init/:/docker-entrypoint-initdb.d/
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1

  dev-redis:
    image: redis:${REDIS_VERSION}
    container_name: dev-redis
    ports:
      - "6379:6379"
    restart: always

  dev-rabbitmq:
    container_name: dev-rabbitmq
    image: rabbitmq:${RABBITMQ_VERSION}
    volumes:
      - $PWD/rabbitmq/data:/var/lib/rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=root  # 账号
      - RABBITMQ_DEFAULT_PASS=123456  # 密码
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    restart: always

  dev-loki:
    image: grafana/loki:${LATEST}
    container_name: dev-loki
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    ports:
      - 3100:3100

  dev-promtail:
    image: grafana/promtail:${LATEST}
    container_name: dev-promtail
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8

  dev-prometheus:
    image: prom/prometheus:${LATEST}
    container_name: dev-prometheus
    volumes:
      - $PWD/prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - dev-nacos
    restart: on-failure

  dev-grafana:
    container_name: dev-grafana
    image: grafana/grafana:${LATEST}
    ports:
      - "3000:3000"
    restart: on-failure

  dev-sentinel:
    image: fxbin/sentinel-dashboard:${SENTINEL_VERSION}
    container_name: dev-sentinel
    ports:
      - "8858:8858"
    expose:
      - "8858"
    restart: on-failure

  dev-es:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: dev-es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "TAKE_FILE_OWNERSHIP=true" #volumes 挂载权限 如果不想要挂载es文件改配置可以删除
      - "discovery.type=single-node" #单机模式启动
      - "TZ=Asia/Shanghai" # 设置时区
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 设置jvm内存大小
    ulimits:
      memlock:
        soft: -1
        hard: -1

  dev-kibana:
    image: kibana:${ELASTICSEARCH_VERSION}
    container_name: dev-kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://dev-es:9200
      - I18N_LOCALE=zh-CN
    ports:
      - 5601:5601
    links:
      - "dev-es"

  dev-web:
    image: httpd
    container_name: dev-web
    ports:
      - "1080:80" #避免和默认的80端口冲突
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 172.18.0.15:24224
        tag: httpd.access

  fluentd:
#    build: ./fluentd
    image: fluent/fluentd:me
    container_name: fluentd
    volumes:
      - $PWD/fluentd/conf/:/fluentd/etc/
    environment:
      - TZ=Asia/Shanghai
    logging:
        driver: "json-file"
        options:
            max-size: 100m
    links:
      - "dev-es"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  dev-skywalking-oap:
    image: apache/skywalking-oap-server:${SKYWALKING_OAP_VERSION}
    container_name: dev-skywalking-oap
    restart: always
    depends_on:
      - dev-es
    links:
      - dev-es
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: dev-es:9200

  dev-skywalking-ui:
    image: apache/skywalking-ui:${SKYWALKING_UI_VERSION}
    container_name: dev-skywalking-ui
    restart: always
    depends_on:
      - dev-skywalking-oap
    links:
      - dev-skywalking-oap
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: http://dev-skywalking-oap:12800
